#!/bin/bash

echo "
=========================================
  	  $(tput setab 5)WELCOME TO HANGMAN!$(tput sgr0)
=========================================

A secret word has been chosen!

Can you uncover it before the hangman is
fully drawn?

Enter one letter at a time. Correct guesses
reveal the word, while incorrect guesses
cost you one attempt.

Let's see how many games you can win!

=========================================
	       $(tput setab 5)Good luck!$(tput sgr0)
========================================="
echo 

MAX_GUESSES=6
GUESSES_LEFT=6
RANDOM_WORD="$(egrep "^[a-z]{5,8}$" /usr/share/dict/words | sort -R | head -n 1)" 

while [[ MAX_GUESS != 0 ]]
do
	echo"you have have $MAX_GUESSES guesses."
	((MAX_GUESSES--))
	
